version: "3"

services:
    api:
        image: avian-influenza
        build: ./api
        volumes:
            - ./api:/usr/src/app
        environment:
            NODE_ENV: development
        ports:
            - 8080:8080

